apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-gateway-route
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    gitops: cluster-config
spec:
  destination:
    namespace: openshift-ingress
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/cluster-config/openshift-ingress/gateway-routes/ocpair03
    repoURL: https://github.com/ansonmez/ai-accelerator.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
