apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../instance/overlays/only-nvidia/kustomization.yaml

patches:
  - target:
      kind: Subscription
      name: nfd
    path: patch-channel.yaml
