apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../instance/overlays/default

patches:
  - target:
      kind: Subscription
      name: gpu-operator-certified
    path: patch-channel.yaml
