apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default
spec:
  components:
   dashboard:
     managementState: Managed
   aipipelines:
     managementState: Managed
   feastoperator:
     managementState: Managed
   kserve:
     managementState: Managed
   llamastackoperator:
     managementState: Managed
   kueue:
     managementState: Removed
   modelregistry:
     managementState: Managed
     registriesNamespace: rhoai-model-registries
   ray:
     managementState: Removed
   workbenches:
     managementState: Managed
   trainingoperator:
     managementState: Managed
   trustyai:
     managementState: Managed
