apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tgis
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: tgis
spec:
  predictor:
    maxReplicas: 0
    minReplicas: 0
    model:
      modelFormat:
        name: pytorch
      name: ""
      runtime: tgis
      storage:
        key: aws-connection-tgis
        path: models/flan-t5-small
